### ISSUE TITLE
Webserver

### ISSUE THREAD

**Issue by darrepac** [xlyric/Domoticz-control-with-esp8266-for-Robotdyn-AC-Light-dimmer-Module#3]
Hi

I guess I am missing something basic but I cannot make the web server to work.
The portal was working good, I am now connected to my WiFi.
If I do MYIP/state, I have an output
But http://MYIP is doing an error 404 while it should access the webserver.

I guess I have an issue with webserver. do I have to do something special with the files in /data folder? in the code, should the file path should not be /data/index.html instead of index.html? (well I tried and the answer is no ;) )

Any hint welcome, I guess it is something basic but it may help others that's why I put it here.

**Comment by darrepac** [comment]
Solution is here: https://github.com/esp8266/arduino-esp8266fs-plugin/

**Comment by xlyric** [comment]
hi, 

the website need to be upload in the SPIFFS zone, ( the filesystem ) 
in the IDE arduino : tools  - ESP8266 Sketch Data Upload 
it will upload all html files in the root filesystem  / 

or 
esptool.py --port com3 --baud 256000 write_flash 0x00200000 spiffs.img 
if you have compiled the spiffs image.
